### PR TITLE
Build site

### PR DESCRIPTION
**Pull request by koheiw**
Build after merging #102.

### CODE REVIEW

**Review by stefan-mueller — APPROVED** [review]
Looks good, @koheiw and @sarahashleyking.

@koheiw, I added the acknowledgements – could you check the changes, rebuild the website, and merge the built website to master?

**Comment by koheiw** [comment]
I rebuilt the site. Let me know if there is a better way to link to the LSX package website (https://github.com/quanteda/tutorials.quanteda.io/pull/104/commits/6b22f6b90e1e9955829ffef00b2cdf8a9ee4b5e6).

**Comment by stefan-mueller** [comment]
> I rebuilt the site. Let me know if there is a better way to link to the LSX package website ([6b22f6b](https://github.com/quanteda/tutorials.quanteda.io/commit/6b22f6b90e1e9955829ffef00b2cdf8a9ee4b5e6)).

For consistency, I'd probably use the output of `citation("LSX")`. If not, you could adjust the citation record in your package.

```
> citation("LSX")

To cite package ‘LSX’ in publications use:

  Watanabe K (2023). _LSX: Semi-Supervised
  Algorithm for Document Scaling_. R package
  version 1.3.0,
  <https://CRAN.R-project.org/package=LSX>.

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {LSX: Semi-Supervised Algorithm for Document Scaling},
    author = {Kohei Watanabe},
    year = {2023},
    note = {R package version 1.3.0},
    url = {https://CRAN.R-project.org/package=LSX},
  }
```

**Comment by koheiw** [comment]
It makes sense to use the citation information if the pages are package vignettes, but they are not becasue they take too long to run on CRAN. They are just pages of a pkgdown website...

**Pull request merged**
